Add Toggleable offline mode warning
PrismarineTeam/Prismarine pull request #20
Opened 2022-10-25 14:47 UTC by imirochi

This patch add config to toggle offline mode warning message when the server is running in offline mode, which is can be ignored safely if using proxy software like Bungee or Velocity.

2022-10-26 08:53 UTC, AlphaKR93 approved these changes

2022-10-29 16:41 UTC, AlphaKR93 requested changes
Rebase required

2022-11-04 18:21 UTC, imirochi commented
Updated to latest commit

2022-11-05 12:45 UTC, AlphaKR93 approved these changes

2022-11-05 12:45 UTC, merged